`timescale 1ns / 1ps

module cache_rreq_bridge #(
    parameter BLK_LEN = 4,
    parameter ENFORCE_STORE_ORDER = 0,
    // CPU and SRAM clocks are generated by the same MMCM but their fractional
    // ratio creates near-coincident edges.  The DCache mailbox therefore uses
    // a falling-edge event synchronizer followed by the normal rising-edge
    // SRAM request registers, while its payload is held until the handshake
    // completes.  The two receiving edges are 9.760 ns apart.  ICache retains
    // the deeper dual-clock FIFOs.
    parameter RELATED_CLOCK_MAILBOX = 0
)(
    input  wire         cpu_rstn,
    input  wire         bus_rstn,
    input  wire         cpu_clk,
    input  wire         cpu_ready,
    input  wire         bus_ready,
    input  wire         w_hold,
    input  wire         r_hold,

    output wire         dev_rrdy,
    input  wire         cpu_ren,
    input  wire [31:0]  cpu_raddr,
    // Per-request burst policy.  A short request returns only the demanded
    // word; a normal request wraps across the complete BLK_LEN cache line.
    input  wire         cpu_short,
    input  wire [ 7:0]  cpu_order_tag,
    input  wire         cpu_strict_order,
    output wire         dev_rvalid,
    output wire [31:0]  dev_rdata,
    output wire         dev_r2_use_rd,

    input  wire         bus_uclk,
    input  wire [ 7:0]  bus_order_done,
    output wire         bus_en,
    output wire [31:0]  bus_raddr,
    input  wire [31:0]  bus_rdata
);

    // Instruction-fetch second-source metadata is inexpensive in the 51 MHz
    // SRAM domain but timing-critical after the response reaches the 150 MHz
    // CPU domain.  Carry it beside every read response; DCache ignores it.
    function r2_use_rd_decode;
        input [31:0] data;
        begin
            r2_use_rd_decode =
                (data[31:24] == 8'h04) ||
                ((data[31:24] == 8'h29) &&
                 !(data[23] && data[22])) ||
                (data[31:27] == 5'b01011) ||
                (data[31:28] == 4'b0110);
        end
    endfunction

    // ---------------------------------------------------------------------
    // CPU -> SRAM request transport.  A cache can have one outstanding miss.
    // ---------------------------------------------------------------------
    wire [41:0] req_payload;
    wire [31:0] req_addr = req_payload[31:0];
    wire        req_short = req_payload[32];
    wire [ 7:0] req_order_tag = req_payload[40:33];
    wire        req_strict_order = req_payload[41];
    wire        req_empty;
    wire        req_full;
    wire        req_pop;
    reg         pending_cpu;

    wire req_accept = cpu_ren && dev_rrdy;
    assign dev_rrdy = cpu_ready && !pending_cpu && !req_full;

    generate
        if (RELATED_CLOCK_MAILBOX) begin : g_related_req_mailbox
            // The payload is written once and held until the complete response
            // returns.  The event first enters an ASYNC_REG at the falling bus
            // edge.  The ordinary rising-edge burst/SRAM registers are the
            // second receiving stage half a bus period later.
            reg [41:0] req_payload_cpu;
            reg        req_toggle_cpu;
            (* ASYNC_REG = "TRUE", SHREG_EXTRACT = "NO" *)
            reg        req_toggle_bus_neg;
            reg        req_toggle_seen_bus;

            assign req_payload = req_payload_cpu;
            assign req_empty = req_toggle_bus_neg == req_toggle_seen_bus;
            assign req_full = 1'b0;

            // While no request is outstanding, continuously preload the
            // mailbox payload.  req_accept can only be true while
            // pending_cpu is false, so the accepted address is still sampled
            // on the very same edge that flips the event toggle.  Once the
            // request is pending the payload remains stable until its final
            // response.  This removes the deep DCache request-accept cone from
            // all 42 payload clock enables without adding a request cycle.
            always @(posedge cpu_clk or negedge cpu_rstn) begin
                if (!cpu_rstn) begin
                    req_payload_cpu <= 42'b0;
                    req_toggle_cpu  <= 1'b0;
                end else begin
                    if (!pending_cpu)
                        req_payload_cpu <= {cpu_strict_order, cpu_order_tag,
                                            cpu_short, cpu_raddr};
                    if (req_accept)
                        req_toggle_cpu <= !req_toggle_cpu;
                end
            end

`ifndef SYNTHESIS
            reg [41:0] req_payload_cpu_prev;
            reg [41:0] accepted_payload_prev;
            reg        req_accept_prev;
            always @(posedge cpu_clk) begin
                if (!cpu_rstn) begin
                    req_payload_cpu_prev <= 42'b0;
                    accepted_payload_prev <= 42'b0;
                    req_accept_prev <= 1'b0;
                end else begin
                    if (req_accept_prev &&
                        (req_payload_cpu !== accepted_payload_prev))
                        $fatal(1, "read mailbox did not capture accepted payload");
                    if (pending_cpu && !req_accept_prev &&
                        (req_payload_cpu !== req_payload_cpu_prev))
                        $fatal(1, "read mailbox payload changed while pending");
                    req_payload_cpu_prev <= req_payload_cpu;
                    req_accept_prev <= req_accept;
                    if (req_accept)
                        accepted_payload_prev <=
                            {cpu_strict_order, cpu_order_tag,
                             cpu_short, cpu_raddr};
                end
            end
`endif

            always @(posedge bus_uclk or negedge bus_rstn) begin
                if (!bus_rstn) begin
                    req_toggle_seen_bus <= 1'b0;
                end else begin
                    if (req_pop)
                        req_toggle_seen_bus <= req_toggle_bus_neg;
                end
            end

            always @(negedge bus_uclk or negedge bus_rstn) begin
                if (!bus_rstn)
                    req_toggle_bus_neg <= 1'b0;
                else
                    req_toggle_bus_neg <= req_toggle_cpu;
            end
        end else begin : g_async_req_fifo
            async_fifo #(
                .DATA_WIDTH (42)
            ) u_rreq_fifo (
                .wr_rstn (cpu_rstn),
                .wr_clk  (cpu_clk),
                .wr_en   (req_accept),
                .din     ({cpu_strict_order, cpu_order_tag,
                           cpu_short, cpu_raddr}),
                .full    (req_full),
                .rd_rstn (bus_rstn),
                .rd_clk  (bus_uclk),
                .rd_en   (req_pop),
                .dout    (req_payload),
                .empty   (req_empty)
            );
        end
    endgenerate

    // ---------------------------------------------------------------------
    // SRAM-domain burst engine.
    //
    // A request is popped only while this engine is idle.  issue_count is
    // advanced only when an address is actually accepted by the shared bus,
    // so read/write arbitration can pause a burst without losing its state.
    // ---------------------------------------------------------------------
    localparam WORD_INDEX_WID = (BLK_LEN > 1) ? $clog2(BLK_LEN) : 1;

    reg        burst_active;
    reg [31:0] active_addr;
    reg [ 7:0] issue_count;

    wire bus_available = bus_ready && !(w_hold || r_hold);
    wire store_order_ready = !ENFORCE_STORE_ORDER || !req_strict_order ||
                             (req_order_tag == bus_order_done);
    wire start_issue    = bus_available && !burst_active && !req_empty &&
                          store_order_ready;
    wire burst_issue    = bus_available &&  burst_active;
    wire read_issue     = start_issue || burst_issue;
    assign req_pop      = start_issue;

    wire start_peripheral = (req_addr[31:16] == 16'h1F00) ||
                            (req_addr[31:16] == 16'hBFD0);
    wire active_peripheral = (active_addr[31:16] == 16'h1F00) ||
                             (active_addr[31:16] == 16'hBFD0);

    wire [31:0] start_word_addr  = {2'b0, req_addr[31:2]};
    wire [31:0] active_word_addr = {2'b0, active_addr[31:2]};
    wire [WORD_INDEX_WID-1:0] burst_word_index =
        active_word_addr[WORD_INDEX_WID-1:0] +
        issue_count[WORD_INDEX_WID-1:0];
    wire [31:0] burst_word_addr =
        {active_word_addr[31:WORD_INDEX_WID], burst_word_index};

    wire issue_last = start_issue
                    ? (start_peripheral || req_short || (BLK_LEN == 1))
                    : (active_peripheral || (issue_count == BLK_LEN-1));

    always @(posedge bus_uclk or negedge bus_rstn) begin
        if (!bus_rstn) begin
            burst_active <= 1'b0;
            active_addr  <= 32'b0;
            issue_count  <= 8'b0;
        end else if (start_issue) begin
            active_addr <= req_addr;
            if (start_peripheral || req_short || (BLK_LEN == 1)) begin
                burst_active <= 1'b0;
                issue_count  <= 8'b0;
            end else begin
                burst_active <= 1'b1;
                issue_count  <= 8'd1;
            end
        end else if (burst_issue) begin
            if (issue_last) begin
                burst_active <= 1'b0;
                issue_count  <= 8'b0;
            end else begin
                issue_count <= issue_count + 1'b1;
            end
        end
    end

    assign bus_en = read_issue;
    assign bus_raddr = start_issue
                     ? (start_peripheral ? req_addr : start_word_addr)
                     : (active_peripheral ? active_addr : burst_word_addr);

    // SRAM data is returned one bus clock after its address.  Carry the last
    // marker beside the data across the response FIFO.
    reg read_issue_r;
    reg read_issue_last_r;
    always @(posedge bus_uclk or negedge bus_rstn) begin
        if (!bus_rstn) begin
            read_issue_r      <= 1'b0;
            read_issue_last_r <= 1'b0;
        end else begin
            read_issue_r <= read_issue;
            if (read_issue)
                read_issue_last_r <= issue_last;
        end
    end

    wire        resp_push = read_issue_r;
    wire        resp_last_bus = read_issue_last_r;
    wire [33:0] resp_dout;
    wire        resp_full;
    wire        resp_empty;
    wire        resp_pop;

    generate
        if (RELATED_CLOCK_MAILBOX) begin : g_related_resp_mailbox
            // SRAM responses are at most one per SRAM clock and the CPU clock
            // is faster.  The event first enters a falling-edge ASYNC_REG and
            // is sampled again at the next rising edge.  Consumption occurs on
            // the following rising edge, giving DCache a complete CPU period
            // instead of an unrouteable half-period response path.
            reg [33:0] resp_payload_bus;
            reg        resp_toggle_bus;
            (* ASYNC_REG = "TRUE", SHREG_EXTRACT = "NO" *)
            reg        resp_toggle_cpu1;
            (* ASYNC_REG = "TRUE", SHREG_EXTRACT = "NO" *)
            reg        resp_toggle_cpu2;
            reg        resp_toggle_seen_cpu;

            assign resp_dout = resp_payload_bus;
            assign resp_empty = resp_toggle_cpu2 == resp_toggle_seen_cpu;
            assign resp_full = 1'b0;
            assign resp_pop = cpu_ready && !resp_empty;

            always @(posedge bus_uclk or negedge bus_rstn) begin
                if (!bus_rstn) begin
                    resp_payload_bus <= 34'b0;
                    resp_toggle_bus  <= 1'b0;
                end else if (resp_push) begin
                    resp_payload_bus <= {resp_last_bus,
                                         r2_use_rd_decode(bus_rdata),
                                         bus_rdata};
                    resp_toggle_bus <= !resp_toggle_bus;
                end
            end

            // The first response synchronizer remains on the falling edge so
            // it receives a full half-cycle of metastability settling time.
            // cpu_rstn is synchronously released; reset these consuming
            // rising-edge stages synchronously to avoid recovery arcs from a
            // CDC status bit into DCache BRAM/state controls.
            always @(posedge cpu_clk) begin
                if (!cpu_rstn) begin
                    resp_toggle_cpu2     <= 1'b0;
                    resp_toggle_seen_cpu <= 1'b0;
                end else begin
                    resp_toggle_cpu2 <= resp_toggle_cpu1;
                    if (resp_pop)
                        resp_toggle_seen_cpu <= resp_toggle_cpu2;
                end
            end

            always @(negedge cpu_clk or negedge cpu_rstn) begin
                if (!cpu_rstn)
                    resp_toggle_cpu1 <= 1'b0;
                else
                    resp_toggle_cpu1 <= resp_toggle_bus;
            end
        end else begin : g_async_resp_fifo
            assign resp_pop = cpu_ready && !resp_empty;

            async_fifo #(
                .DATA_WIDTH (34),
                .FIFO_DEPTH (16)
            ) u_rresp_fifo (
                .wr_rstn (bus_rstn),
                .wr_clk  (bus_uclk),
                .wr_en   (resp_push && !resp_full),
                .din     ({resp_last_bus, r2_use_rd_decode(bus_rdata),
                           bus_rdata}),
                .full    (resp_full),
                .rd_rstn (cpu_rstn),
                .rd_clk  (cpu_clk),
                .rd_en   (resp_pop),
                .dout    (resp_dout),
                .empty   (resp_empty)
            );
        end
    endgenerate

    // async_fifo is first-word fall-through.  Once its synchronized write
    // pointer makes resp_empty low, the head data has already been stable for
    // two CPU clock edges.  Let the cache consume that head on the same edge
    // which advances the read pointer instead of registering it for one extra
    // CPU cycle.  This removes one cycle from every miss response without
    // weakening the two-flop CDC protection on the FIFO pointers.
    assign dev_rvalid = resp_pop;
    assign dev_rdata  = resp_dout[31:0];
    assign dev_r2_use_rd = resp_dout[32];

    always @(posedge cpu_clk) begin
        if (!cpu_rstn) begin
            pending_cpu <= 1'b0;
        end else begin
            if (resp_pop && resp_dout[33])
                pending_cpu <= 1'b0;
            else if (req_accept)
                pending_cpu <= 1'b1;
        end
    end


`ifndef SYNTHESIS
    always @(posedge cpu_clk) begin
        if (cpu_rstn && dev_rvalid &&
            (dev_r2_use_rd !== r2_use_rd_decode(dev_rdata)))
            $fatal(1, "read-response r2 metadata differs from payload");
    end
`endif

endmodule
